### ISSUE TITLE
New badge for champions programme

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/badges#10]
Ping @yabellini @noamross @maelle

**Comment by mpadge** [comment]
@noamross @yabellini New badge has been created here (as `./svgs/champion.svg`):

![](https://raw.githubusercontent.com/ropensci-org/badges/main/svgs/champion.svg)

It can be modified very easily, so let's first discuss what it should look like, before developing any deployment strategies.

**Comment by yabellini** [comment]
@mpadge I like a lot :-). 
What do you think on have the words "Champions Program", so we can also give a badge to mentors and training materials?

**Comment by noamross** [comment]
I like "Champions Program". We had thought of this as primarily a badge for packages/repos that the champions develop as part of the program (as this idea emerged from the idea that some champions projects would otherwise be out-of-scope for peer review). I'm not sure what mentors would do with it.

**Comment by mpadge** [comment]
Only potential problem would be that it's much longer:

![](https://raw.githubusercontent.com/ropensci-org/badges/main/svgs/champion.svg)
![](https://raw.githubusercontent.com/ropensci-org/badges/main/svgs/champions-program.svg)

**Comment by noamross** [comment]
I don't think the length is an issue.  Another Q: What should this badge link back/refer to?  Maybe a page/post on the website where we list the outcomes champion projects?

**Comment by yabellini** [comment]
We are going to have a wrap-up of all the projects, so it will be a blog post.  If we continue with the program then we will need a website for the program and then we can link to the cohort page.

**Comment by yabellini** [comment]
Can I request champions to use the badge in their readme on their package repos? I already share with some of them.

**Comment by mpadge** [comment]
Yes, they can be used, but we should first decide which one of the two options we're going to keep, and make sure we remove the other one. Please vote:

- :+1: ![](https://raw.githubusercontent.com/ropensci-org/badges/main/svgs/champion.svg)
- :-1: ![](https://raw.githubusercontent.com/ropensci-org/badges/main/svgs/champions-program.svg)

@yabellini @noamross @karthik @maelle @jeroen @steffilazerte

**Comment by karthik** [comment]
Can we change the color so it doesn't get confused with the peer review badge? And also has a more distinct identity

**Comment by mpadge** [comment]
Easy, just change `fill="#4c1"` in the [svg source](https://github.com/ropensci-org/badges/blob/main/svgs/champions-program.svg) to something else. https://www.color-hex.com/color/44cc11 - either let me know something else, or PR with change to Line 11 of the svg. (You can't view the code on GitHub, because it always defaults to diplaying svgs, never showing code.)

**Comment by karthik** [comment]
Right, I understand how to change it (I made the original badges). I meant more that we should pick a color to differentiate it.

**Comment by yabellini** [comment]
We have used the rOpenSci light blue in almost everything for the champions program.  The cons are that it is the color for the community, not only for the champions program; the pro is that it is the rOpenSci color. 

Another option is that I create options with different color palettes (blue, orange, purple) and ask champions and mentors to give us their opinions (vote on which one will be the color).

**Comment by yabellini** [comment]
I shared color options with champions and mentors to choose from.  I will let you know when we have a color.

**Comment by yabellini** [comment]
This was the most voted color by champions and mentors: #D36BE7
