### ISSUE TITLE
Peer review badge not rendering properly on github

### ISSUE THREAD

**Issue by willgearty** [ropensci-org/badges#19]
The peer review badge for {rredlist} currently appears fine on it's own:
https://badges.ropensci.org/663_status.svg
![image](https://github.com/user-attachments/assets/71177c77-9659-479f-9342-64d668348540)

And it looks fine on the pkgdown site:
https://docs.ropensci.org/rredlist/index.html
![image](https://github.com/user-attachments/assets/d5ff01e7-2602-4e0d-b58a-36f922e7ee68)

But it doesn't render properly on GitHub:
https://github.com/ropensci/rredlist/
![image](https://github.com/user-attachments/assets/59977f19-30a3-4b66-9ddc-82e9ab0630e7)

I've checked with multiple browsers (Chrome, Edge, and the GitHub android app), and I have no idea what's going on or why the behavior would change on GitHub, so I figured I would report it here.

**Comment by mpadge** [comment]
Thanks @willgearty, but I note that it all seems okay now on every system-browser combination i can find. I also note, however, that the badge server did encounter an [unexpected error on the GitHub side](https://github.com/ropensci-org/badges/actions/runs/11588119226/job/32261230306), which  may have caused that temporary glitch? If everything is now okay for you, feel free to close issue, or comment further to the contrary if not :wink:

**Comment by willgearty** [comment]
Yep, looks good to me now, thanks!
